export const ErrorCode = {
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  COMPANY_REQUEST_NOT_FOUND: "COMPANY_REQUEST_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    COMPANY_REQUEST_CANNOT_BE_UPDATED:
    "COMPANY_REQUEST_CANNOT_BE_UPDATED",
    COMPANY_REQUEST_ALL_DOCUMENTS_REQUIRED:
  "COMPANY_REQUEST_ALL_DOCUMENTS_REQUIRED",
 DOCUMENT_FILE_REQUIRED:"DOCUMENT_FILE_REQUIRED",
 UNAUTHORIZED:"UNAUTHORIZED",
DOCUMENT_NOT_FOUND:"DOCUMENT_NOT_FOUND",
SUBSCRIPTION_PLAN_NOT_FOUND:"SUBSCRIPTION_PLAN_NOT_FOUND",
All_READY_SUBSCRIBED:"All_READY_SUBSCRIBED"
} as const;