export const ErrorCode = {
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  COMPANY_REQUEST_NOT_FOUND: "COMPANY_REQUEST_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    COMPANY_REQUEST_CANNOT_BE_UPDATED:
    "COMPANY_REQUEST_CANNOT_BE_UPDATED",
    COMPANY_REQUEST_ALL_DOCUMENTS_REQUIRED:
  "COMPANY_REQUEST_ALL_DOCUMENTS_REQUIRED",
 DOCUMENT_FILE_REQUIRED:"DOCUMENT_FILE_REQUIRED",
 UNAUTHORIZED:"UNAUTHORIZED",
DOCUMENT_NOT_FOUND:"DOCUMENT_NOT_FOUND",
SUBSCRIPTION_PLAN_NOT_FOUND:"SUBSCRIPTION_PLAN_NOT_FOUND",
All_READY_SUBSCRIBED:"All_READY_SUBSCRIBED",
COMPY_NOT_FOUND:"COMPY_NOT_FOUND",
SUBSCRIPTION_PLAN_NOT_ACTIVE:"SUBSCRIPTION_PLAN_NOT_ACTIVE",
INVALID_PAYMENT_SIGNATURE:"INVALID_PAYMENT_SIGNATURE",
PAYMENT_NOT_FOUND:"PAYMENT_NOT_FOUND",
COMPANY_ADMIN_NOT_FOUND:"COMPANY_ADMIN_NOT_FOUND",
SUBSCRIPTION_PLAN_ALREADY_EXISTS:"SUBSCRIPTION_PLAN_ALREADY_EXISTS",
DEPARTMENT_CODE_ALREADY_EXISTS : "DEPARTMENT_CODE_ALREADY_EXISTS",

DEPARTMENT_ALREADY_EXISTS :"DEPARTMENT_ALREADY_EXISTS",

DEPARTMENT_NOT_FOUND:"DEPARTMENT_NOT_FOUND",
INVALID_INPUT:"INVALID_INPUT"
} as const;