export const ErrorCode = {
  ACCOUNT_NOT_FOUND: "ACCOUNT_NOT_FOUND",
  COMPANY_REQUEST_NOT_FOUND: "COMPANY_REQUEST_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    COMPANY_REQUEST_CANNOT_BE_UPDATED:
    "COMPANY_REQUEST_CANNOT_BE_UPDATED",
    COMPANY_REQUEST_ALL_DOCUMENTS_REQUIRED:
  "COMPANY_REQUEST_ALL_DOCUMENTS_REQUIRED",
 DOCUMENT_FILE_REQUIRED:"DOCUMENT_FILE_REQUIRED"
} as const;