
export enum RegistrationStep {
  ADMIN_DETAILS = "ADMIN_DETAILS",
  COMPANY_DETAILS = "COMPANY_DETAILS",
  COMPANY_LOCATION="COMPANY_LOCATION",
  DOCUMENTS = "DOCUMENTS",
  COMPLETED = "COMPLETED",
}