export enum CompanyRequestTimelineAction {
  SUBMITTED = "SUBMITTED",
  UNDER_REVIEW = "UNDER_REVIEW",
  MORE_INFO_REQUIRED = "MORE_INFO_REQUIRED",
  RESUBMITTED = "RESUBMITTED",
  DOCUMENT_VERIFIED = "DOCUMENT_VERIFIED",
  DOCUMENT_REJECTED = "DOCUMENT_REJECTED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}